### PR TITLE
Update js.js

### PR DESCRIPTION
**Pull request by Vapsel**
It didn't work with tagName 'div' in 11 line. Fix it to 'DIV'

### CODE REVIEW

**Comment by tischsoic** [comment]
I checked this in both Google Chrome and Opera browsers and my solution works on both, Yours doesn't work on any. :)

**Comment by tischsoic** [comment]
But I will check why my solution works. There must be something wrong, because here:
http://www.w3schools.com/jsref/prop_element_tagname.asp
is stated that "In HTML, the returned value of the tagName property is always in UPPERCASE.".

**Comment by tischsoic** [comment]
I have found probable answer, here:
http://stackoverflow.com/questions/11811426/why-does-the-tagname-dom-property-return-an-uppercase-value 
is stated that:
"Note that lowercase tag names are only explicitly required in XHTML (but not XML), and authors are generally recommended to write lowercase tags for easy porting between HTML/XHTML, as well as improving readability. However, this recommendation doesn't occur in the spec; all it says is that tag names are case-insensitive only in HTML as opposed to XHTML and XML."

**Comment by tischsoic** [comment]
Now the question is wheather the header and file extensions are correct. Because of this is solution to problem from JiTW's test, I really don't know.

**Comment by Vapsel** [comment]
So, if you set on file extension "xhtml" you need to use lowercase. But I set it to "html", so your solution don't work for me and my solution don't work for you :) It's my mistake when I created XHTML document

**Comment by tischsoic** [comment]
I am happy, we've reached agreement!

**Pull request closed without merging**
